<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Winknow.ControlService-f7ef0a21-dcb8-4d6a-8bc9-5426e39b65c6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Winknow.ControlService.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Winknow.Core\Winknow.Core.csproj" />
    <ProjectReference Include="..\Winknow.DeviceSecurity\Winknow.DeviceSecurity.csproj" />
    <ProjectReference Include="..\Winknow.Ipc\Winknow.Ipc.csproj" />
    <ProjectReference Include="..\Winknow.Logging\Winknow.Logging.csproj" />
    <ProjectReference Include="..\Winknow.Network\Winknow.Network.csproj" />
    <ProjectReference Include="..\Winknow.Policy\Winknow.Policy.csproj" />
    <ProjectReference Include="..\Winknow.ProcessControl\Winknow.ProcessControl.csproj" />
    <ProjectReference Include="..\Winknow.Security\Winknow.Security.csproj" />
  </ItemGroup>
</Project>

