using System.Security.Cryptography;
using System.Text;

namespace Winknow.Core;

/// <summary>
/// Provides common cryptographic helper functions.
/// </summary>
public static class SecurityUtils
{
    /// <summary>Computes a SHA-256 hash for binary data.</summary>
    /// <param name="data">The data to hash.</param>
    /// <returns>An uppercase hexadecimal hash.</returns>
    public static string ComputeSha256Hash(byte[] data)
    {
        ArgumentNullException.ThrowIfNull(data);
        return Convert.ToHexString(SHA256.HashData(data));
    }

    /// <summary>Computes a SHA-256 hash for UTF-8 text.</summary>
    /// <param name="text">The text to hash.</param>
    /// <returns>An uppercase hexadecimal hash.</returns>
    public static string ComputeSha256Hash(string text)
    {
        ArgumentNullException.ThrowIfNull(text);
        return ComputeSha256Hash(Encoding.UTF8.GetBytes(text));
    }

    /// <summary>Computes a SHA-256 hash for a file.</summary>
    /// <param name="filePath">The path of the file to hash.</param>
    /// <returns>An uppercase hexadecimal hash.</returns>
    public static string ComputeSha256HashFile(string filePath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(filePath);
        var normalizedPath = Path.GetFullPath(filePath);
        using var stream = File.OpenRead(normalizedPath);
        return Convert.ToHexString(SHA256.HashData(stream));
    }

    /// <summary>Generates cryptographically secure random bytes.</summary>
    /// <param name="count">The number of bytes to generate.</param>
    /// <returns>The generated bytes.</returns>
    public static byte[] GenerateRandomBytes(int count)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(count);
        return RandomNumberGenerator.GetBytes(count);
    }

    /// <summary>Generates a 16-byte nonce.</summary>
    /// <returns>The generated nonce.</returns>
    public static byte[] GenerateNonce() => GenerateRandomBytes(16);

    /// <summary>
    /// 固定时间字节数组比较（防时序侧信道）。
    /// 用于比较 SID、摘要等敏感值；长度不同时仍执行完整比较路径。
    /// </summary>
    public static bool FixedTimeEquals(byte[] left, byte[] right)
    {
        ArgumentNullException.ThrowIfNull(left);
        ArgumentNullException.ThrowIfNull(right);
        if (left.Length != right.Length)
        {
            // 长度不同也走一遍比较，避免通过长度差异提前泄露
            System.Security.Cryptography.CryptographicOperations.FixedTimeEquals(
                left, left.Length == right.Length ? right : left);
            return false;
        }
        return System.Security.Cryptography.CryptographicOperations.FixedTimeEquals(left, right);
    }

    /// <summary>
    /// 固定时间字符串比较（UTF-8 编码后逐字节比较，防时序侧信道）。
    /// </summary>
    public static bool FixedTimeEquals(string left, string right)
    {
        ArgumentNullException.ThrowIfNull(left);
        ArgumentNullException.ThrowIfNull(right);
        return FixedTimeEquals(Encoding.UTF8.GetBytes(left), Encoding.UTF8.GetBytes(right));
    }
}
