using System.Security.Cryptography;
using System.Text;

namespace Winknow.Core;

/// <summary>
/// Provides common cryptographic helper functions.
/// </summary>
public static class SecurityUtils
{
    /// <summary>Computes a SHA-256 hash for binary data.</summary>
    /// <param name="data">The data to hash.</param>
    /// <returns>An uppercase hexadecimal hash.</returns>
    public static string ComputeSha256Hash(byte[] data)
    {
        ArgumentNullException.ThrowIfNull(data);
        return Convert.ToHexString(SHA256.HashData(data));
    }

    /// <summary>Computes a SHA-256 hash for UTF-8 text.</summary>
    /// <param name="text">The text to hash.</param>
    /// <returns>An uppercase hexadecimal hash.</returns>
    public static string ComputeSha256Hash(string text)
    {
        ArgumentNullException.ThrowIfNull(text);
        return ComputeSha256Hash(Encoding.UTF8.GetBytes(text));
    }

    /// <summary>Computes a SHA-256 hash for a file.</summary>
    /// <param name="filePath">The path of the file to hash.</param>
    /// <returns>An uppercase hexadecimal hash.</returns>
    public static string ComputeSha256HashFile(string filePath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(filePath);
        var normalizedPath = Path.GetFullPath(filePath);
        using var stream = File.OpenRead(normalizedPath);
        return Convert.ToHexString(SHA256.HashData(stream));
    }

    /// <summary>Generates cryptographically secure random bytes.</summary>
    /// <param name="count">The number of bytes to generate.</param>
    /// <returns>The generated bytes.</returns>
    public static byte[] GenerateRandomBytes(int count)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(count);
        return RandomNumberGenerator.GetBytes(count);
    }

    /// <summary>Generates a 16-byte nonce.</summary>
    /// <returns>The generated nonce.</returns>
    public static byte[] GenerateNonce() => GenerateRandomBytes(16);
}
