<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Winknow.Core\Winknow.Core.csproj" />
    <ProjectReference Include="..\Winknow.Security\Winknow.Security.csproj" />
    <ProjectReference Include="..\Winknow.Logging\Winknow.Logging.csproj" />
  </ItemGroup>

</Project>

